## 7장 텍스트 데이터 다루기

In [1]:
sentences = ['가장 자연스럽고 좋은 영화 였다', '최고의 영화 4편이 기대됨']

In [2]:
type(sentences), len(sentences)

(list, 2)

bow(bag of words) 단어가방으로 전처리

In [3]:
#420
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [4]:
vect.fit(sentences)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [6]:
len(vect.vocabulary_), vect.vocabulary_

(8,
 {'가장': 1,
  '자연스럽고': 5,
  '좋은': 6,
  '영화': 4,
  '였다': 3,
  '최고의': 7,
  '4편이': 0,
  '기대됨': 2})

In [9]:
# desne와는 다르게 텍스트 데이터는 saprse matrix로 메모리 절약
sparse_matrix = vect.transform(sentences)
print(sparse_matrix)

  (0, 1)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 6)	1
  (1, 0)	1
  (1, 2)	1
  (1, 4)	1
  (1, 7)	1


In [11]:
sparse_matrix.toarray()

array([[0, 1, 0, 1, 1, 1, 1, 0],
       [1, 0, 1, 0, 1, 0, 0, 1]], dtype=int64)

In [14]:
from sklearn.datasets import fetch_20newsgroups

In [15]:
news = fetch_20newsgroups()

In [16]:
len(news.data), len(news.target)

(11314, 11314)

In [17]:
print(news.data[0])

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----







In [18]:
print(news.data[1])

From: guykuo@carson.u.washington.edu (Guy Kuo)
Subject: SI Clock Poll - Final Call
Summary: Final call for SI clock reports
Keywords: SI,acceleration,clock,upgrade
Article-I.D.: shelley.1qvfo9INNc3s
Organization: University of Washington
Lines: 11
NNTP-Posting-Host: carson.u.washington.edu

A fair number of brave souls who upgraded their SI clock oscillator have
shared their experiences for this poll. Please send a brief message detailing
your experiences with the procedure. Top speed attained, CPU rated speed,
add on cards and adapters, heat sinks, hour of usage per day, floppy disk
functionality with 800 and 1.4 m floppies are especially requested.

I will be summarizing in the next two days, so please add to the network
knowledge base if you have done the clock upgrade and haven't answered this
poll. Thanks.

Guy Kuo <guykuo@u.washington.edu>



In [19]:
news.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

자연어 뉴스를 배열 vector로 변환

In [20]:
vect = CountVectorizer().fit(news.data)

In [21]:
len(vect.vocabulary_), vect.vocabulary_[:5]

TypeError: unhashable type: 'slice'

In [23]:
sm = vect.transform(news.data)

In [24]:
sm

<11314x130107 sparse matrix of type '<class 'numpy.int64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [25]:
sm.shape

(11314, 130107)

In [26]:
from sklearn.linear_model import LogisticRegression

In [28]:
model = LogisticRegression().fit(sm, news.target)

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [29]:
model.score(sm, news.target)

0.999734841788934

In [30]:
test_set = ['Hi, Major League Base ball, who is winner?']

In [31]:
model.predict(vect.transform(test_set))

array([9])

In [32]:
news.target_names[9]

'rec.sport.baseball'

In [35]:
news.target_names[4]
ect.transform(test_set)

NameError: name 'ect' is not defined

In [34]:
sm_test = ect.transform(test_set)
dm = sm_test[0], toarray
dm.shape

NameError: name 'ect' is not defined

In [ ]:
mo

In [36]:
import konlpy

In [38]:
from konlpy.tag import Kkma
from konlpy.utils import pprint
kkma = Kkma()
pprint(kkma.sentences(u'네, 안녕하세요. 반갑습니다.'))

C:\Users\wtime\Anaconda3\lib\site-packages\jpype\_core.py:210: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)


['네, 안녕하세요.', '반갑습니다.']


In [41]:
#명사
pprint(kkma.nouns(u'질문이나 건의사항은 깃헙 이슈 트래커에 남겨주세요.'))

['질문', '건의', '건의사항', '사항', '깃헙', '이슈', '트래커']


In [40]:
pprint(kkma.pos(u'오류보고는 실행환경, 에러메세지와함께 설명을 최대한상세히!^^'))

[('오류', 'NNG'),
 ('보고', 'NNG'),
 ('는', 'JX'),
 ('실행', 'NNG'),
 ('환경', 'NNG'),
 (',', 'SP'),
 ('에러', 'NNG'),
 ('메세지', 'NNG'),
 ('와', 'JKM'),
 ('함께', 'MAG'),
 ('설명', 'NNG'),
 ('을', 'JKO'),
 ('최대한', 'NNG'),
 ('상세히', 'MAG'),
 ('!', 'SF'),
 ('^^', 'EMO')]


In [44]:
#p445
from konlpy.tag import Okt
okt_tag = Okt()
okt_tag.morphs('질문이나 건의사항은 깃헙 이슈 트레커에 남겨주세요.')

['질문', '이나', '건의', '사항', '은', '깃', '헙', '이슈', '트레커', '에', '남겨주세요', '.']

In [46]:
cv = CountVectorizer(tokenizer=okt_tag.morphs) #문장 > 벡터로 변환할때는 단어 자르는 기능을 konlpy 샤용

In [47]:
sentences = ['안녕 나는 남자야 남자!', '안녕, 나는 여자야 여자!!']

In [48]:
cv.fit(sentences) # 토큰을 잘라서 어휘 사전을 준비합니다.

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x0000013A3F20C860>>,
        vocabulary=None)

In [50]:
sparse_matrix = cv.transform(sentences) #문장을 희소 행렬로 변환

In [51]:
cv = cv.fit(sentences)

In [52]:
cv.vocabulary_

{'안녕': 6, '나': 3, '는': 5, '남자': 4, '야': 7, '!': 0, ',': 2, '여자': 8, '!!': 1}

네이버 영화 리부 추천/비추천 분류

In [53]:
import pandas as pd

C:\Users\wtime\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\wtime\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [54]:
movie = pd.read_csv('ratings_train.txt', delimiter = '\t')

In [55]:
movie.shape

(150000, 3)

In [56]:
movie.head()

id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [57]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
id          150000 non-null int64
document    149995 non-null object
label       150000 non-null int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB


In [60]:
movie.drop(columns='id')

document  label
0                                     아 더빙.. 진짜 짜증나네요 목소리      0
1                       흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2                                       너무재밓었다그래서보는것을추천한다      0
3                           교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4       사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
5           막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화.ㅋㅋㅋ...별반개도 아까움.      0
6                                   원작의 긴장감을 제대로 살려내지못했다.      0
7       별 반개도 아깝다 욕나온다 이응경 길용우 연기생활이몇년인지..정말 발로해도 그것보단...      0
8                                  액션이 없는데도 재미 있는 몇안되는 영화      1
9           왜케 평점이 낮은건데? 꽤 볼만한데.. 헐리우드식 화려함에만 너무 길들여져 있나?      1
10                                       걍인피니트가짱이다.진짜짱이다♥      1
11            볼때마다 눈물나서 죽겠다90년대의 향수자극!!허진호는 감성절제멜로의 달인이다~      1
12                    울면서 손들고 횡단보도 건널때 뛰쳐나올뻔 이범수 연기 드럽게못해      0
13      담백하고 깔끔해서 좋다. 신문기사로만 보다 보면 자꾸 잊어버린다. 그들도 사람이었다...      1
14      취향은 존중한다지만 진짜 내생에 극장에서 본 영화중 가장 노잼 노감동임 스토리도 어...      0
15                                       ㄱ냥 매번 긴장되고 재밋음ㅠㅠ      1
16      참 사람들 웃긴게 바스코가 이기면 락스코라고 까고바비가 이기면 아이돌이라고 깐다.그...      1
17                     굿바이 레닌 표절인것은 이해하는데 왜 뒤로 갈수록 재미없어지냐      0
18          이건 정말 깨알 캐스팅과 질퍽하지않은 산뜻한 내용구성이 잘 버무러진 깨알일드!!♥      1
19                     약탈자를 위한 변명, 이라. 저놈들은 착한놈들 절대 아닌걸요.      1
20              나름 심오한 뜻도 있는 듯. 그냥 학생이 선생과 놀아나는 영화는 절대 아님      1
21                                      보면서 웃지 않는 건 불가능하다      1
22      재미없다 지루하고. 같은 음식 영화인데도 바베트의 만찬하고 넘 차이남....바베트의...      0
23                           절대 평범한 영화가 아닌 수작이라는걸 말씀드립니다.      1
24                                      주제는 좋은데 중반부터 지루하다      0
25           다 짤랐을꺼야. 그래서 납득할 수 없었던거야.. 그럴꺼야.. 꼭 그랬던걸꺼야..      0
26                                     kl2g 고추를 털어버려야 할텐데      1
27                                               카밀라벨 발연기      0
28                                                   재밋는뎅      1
29                 센스있는 연출력..탁월한 캐스팅..90년대의 향수.. 그래서 9점..      1
...                                                   ...    ...
149970                                     한번더보고싶은영화 너무좋음      1
149971                                   완전 고현정의 미친 연기 감동      1
149972                   사랑이라는 감정에 빠진 적이 있던가 반문하게 만드는 걸작.      1
149973      명감독의 지휘 아래 카리스마 빛나는 당대 톱배우들의 암살 대결이 흥미롭게 펼쳐진다      1
149974                                베트남 전통복장 말고는 볼게 없다.      0
149975                                   무지 자극적 에로틱 드라마!!      1
149976  일본은 한국전쟁에 참전한적도 없고 2차세계대전이후 완전 패망했다가 한국전쟁 때 군수...      0
149977                                      무슨말이 더 필요한가..      1
149978  그리 만족스럽진못했어도 7점은 나와야되는것같아 10점줌. 주인공들연기도 훌륭했고 내...      1
149979                                           배우들이 아깝다      0
149980             아, 진짜 웃긴다...프랑스 영화 정말 싫어했었는데 이 영화는 열외~      1
149981  시간이 아깝다. 어린 여주의 연기는 인상적이었고 나중이 기대되어서 좋았고 남주 여주...      0
149982           평점너무낮아서 십점줌ㅋㅋㅋㅋ난진짜재밌던데 이런가벼운영화도 한번씩보면좋을듯      1
149983             그냥생각없이 평점좀 쓰지마 OOO들아 두 배우의연기가 너무맘에 들었다      1
149984     수술할정도로 아파본사람들만이 제대로 동감할수 있는영화..삶의 소중함.과 고마움...      1
149985                        해석하기 나름인 패륜영화. 그래도 이건 아니잖니.      0
149986                               1점도아깝다진짜 개빡친다 내아까운시간      0
149987                                            재미있어요^^      1
149988             와~ 이런 것도 영화라고... 차라리 뮤직비디오를 만드는 게 나을 뻔      0
149989     아직 척편이여서 그런지 모르겠지만 내용 이해 불가50가지 그림자가 뭔지 모르겠습니다      0
149990                                       이걸 영화라고 찎었냐?      0
149991  http://blog.naver.com/oroblast/220215679580 나쁜...      1
149992  공포나 재난영화가 아니라 아예 대놓고 비급 크리쳐개그물임ㅋㅋ 음악 완전 흥겹다ㅋ 5...      0
149993                 For Carl.칼 세이건으로 시작해서 칼 세이건으로 끝난다.      1
149994               디케이드 다음에 더블 다음에 오즈인데 더블은 조금밖에 안나오네요.      1
149995                                인간이 문제지.. 소는 뭔죄인가..      0
149996                                      평점이 너무 낮아서...      1
149997                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 2 c

In [61]:
m = 1000
movie = movie.iloc[:m]

In [62]:
movie.isna().sum()

id          0
document    0
label       0
dtype: int64

In [63]:
X = movie.document
y = movie.label

In [64]:
from konlpy.tag import Okt
okt_tag = Okt()
cv = CountVectorizer(tokenizer=okt_tag.morphs)  # 전처리

In [66]:
cv = cv.fit(X)

In [67]:
len(cv.vocabulary_)

4767

In [68]:
X_sm = cv.transform(X)

In [81]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import RidgeClassifier

In [82]:
scores = cross_val_score(RidgeClassifier(), X_sm, y, cv = 3)
scores

array([0.70658683, 0.6996997 , 0.66066066])

In [83]:
model = RidgeClassifier().fit(X_sm, y)

In [84]:
sentences = ['두시간동안 잘 자고 나왔습니다', '돈이 아깝다']
model.predict(cv.transform(sentences))

array([1, 0], dtype=int64)